### ISSUE TITLE
Here is the Chinese translation of the mod

### ISSUE THREAD

**Issue by 2049716234** [Dunc4nNT/StardewMods#12]
### Summary

Here is the Chinese translation of the mod

### The Problem

Because this mod is now only available in English

### Your Solution

{
  "config.general.page-title": "常规",
  "config.general.general-section": "常规",
  "config.general.catch-fish-retries.name": "重试捕鱼",
  "config.general.catch-fish-retries.tooltip": "mod 会尝试钓到鱼而不是垃圾的次数.",
  "config.general.instant-catch-fish.name": "瞬间抓鱼",
  "config.general.instant-catch-fish.tooltip": "跳过钓鱼小游戏.",
  "config.general.instant-catch-treasure.name": "瞬间抓宝",
  "config.general.instant-catch-treasure.tooltip": "如果钓鱼小游戏中有任何宝藏，即使你错过了它们，也要立即抓住它们.",
  "config.general.always-max-casting-power.name": "始终最大铸造功率",
  "config.general.always-max-casting-power.tooltip": "始终以最大功率投掷钓鱼竿，无论您按住按钮多长时间.",
  "config.general.always-perfect.name": "永远完美",
  "config.general.always-perfect.tooltip": "钓到鱼后总是得到完美的，即使你没有.",
  "config.general.treasure-appearance.name": "宝物出场率",
  "config.general.treasure-appearance.tooltip": "调整捕鱼时宝箱出现的频率.",
  "config.general.always-catch-double.name": "总是抓住双倍的鱼",
  "config.general.always-catch-double.tooltip": "总是钓到双鱼，即使你没有正确的诱饵.",
  "config.general.instant-bite.name": "瞬间咬钩",
  "config.general.instant-bite.tooltip": "鱼投下鱼竿后立即咬钩.",
  "config.general.auto-hook.name": "自动挂钩",
  "config.general.auto-hook.tooltip": "上钩后自动开始卷鱼.",
  "config.general.auto-loot-treasure.name": "自动掠夺宝藏",
  "config.general.auto-loot-treasure.tooltip": "抓到宝藏后自动掠夺并关闭宝藏菜单弹出窗口.",
  "config.general.difficulty-multiplier.name": "难度倍增器",
  "config.general.difficulty-multiplier.tooltip": "标准钓鱼难度乘以的值.",
  "config.general.quality-section": "质量选项",
  "config.general.fish-quality.name": "鱼品品质",
  "config.general.fish-quality.tooltip": "始终以设定的质量捕鱼.",
  "config.general.minimum-fish-quality.name": "最低鱼品质量",
  "config.general.minimum-fish-quality.tooltip": "总是得到一定质量或更好的鱼.",

  "config.attachments.page-title": "附件",
  "config.attachments.general-section": "常规",
  "config.attachments.override-attachment-limit.name": "覆盖附件限制",
  "config.attachments.override-attachment-limit.tooltip": "在产生诱饵和钓具时覆盖钓鱼竿的附着限制.",
  "config.attachments.reset-attachments.name": "重置附件",
  "config.attachments.reset-attachments.tooltip": "未装备钓鱼竿时重置生成的附件和槽位.",
  "config.attachments.bait-section": "诱饵",
  "config.attachments.spawn-bait-when-equipped.name": "装备后生成诱饵",
  "config.attachments.spawn-bait-when-equipped.tooltip": "每当你装备你的鱼竿时，都会生成以下选定的诱饵物品.",
  "config.attachments.spawn-which-bait.name": "诱饵生成",
  "config.attachments.spawn-which-bait.tooltip": "装备鱼竿时自动生成的诱饵.",
  "config.attachments.infinite-bait.name": "无限诱饵",
  "config.attachments.infinite-bait.tooltip": "永远不要用完诱饵.",
  "config.attachments.tackles-section": "钓具",
  "config.attachments.spawn-tackle-when-equipped.name": "装备时生成钓具",
  "config.attachments.spawn-tackle-when-equipped.tooltip": "每当你装备你的钓鱼竿时，都会生成以下选定的钓具物品.",
  "config.attachments.spawn-which-tackle.name": "钓具生成",
  "config.attachments.spawn-which-tackle.tooltip": "装备钓鱼竿时自动生成的钓具.",
  "config.attachments.infinite-tackle.name": "无限钓具",
  "config.attachments.infinite-tackle.tooltip": "钓具永不磨损.",

  "config.enchantments.page-title": "附 魔",
  "config.enchantments.general-section": "常规",
  "config.enchantments.do-add-enchantments.name": "启用添加附魔",
  "config.enchantments.do-add-enchantments.tooltip": "勾选时添加如下设置的附魔.",
  "config.enchantments.reset-enchantments.name": "重置附魔",
  "config.enchantments.reset-enchantments.tooltip": "解除钓鱼竿后将附魔重置为之前的样子.",
  "config.enchantments.enchantments-section": "附 魔",
  "config.enchantments.add-all-enchantments.name": "添加所有附魔",
  "config.enchantments.add-all-enchantments.tooltip": "装备钓鱼竿时添加所有可用的附魔.",
  "config.enchantments.add-auto-hook-enchantment.name": "添加自动钩子附魔",
  "config.enchantments.add-auto-hook-enchantment.tooltip": "装备钓鱼竿时添加自动钩附魔.",
  "config.enchantments.add-efficient-tool-enchantment.name": "添加高效附魔",
  "config.enchantments.add-efficient-tool-enchantment.tooltip": "在装备钓鱼竿时增加高效的工具附魔.",
  "config.enchantments.add-master-enchantment.name": "添加大师附魔",
  "config.enchantments.add-master-enchantment.tooltip": "装备钓鱼竿时添加主附魔.",
  "config.enchantments.add-preserving-enchantment.name": "添加保存附魔",
  "config.enchantments.add-preserving-enchantment.tooltip": "在装备钓鱼竿时增加保存附魔.",

  "config.treasure-appearance-vanilla": "香草",
  "config.treasure-appearance-never": "从不",
  "config.treasure-appearance-always": "总是",

  "config.quality-any": "任何",
  "config.quality-none": "没有",
  "config.quality-silver": "银",
  "config.quality-gold": "金",
  "config.quality-iridium": "铱",

  "message.config-reloaded": "配置文件已重新加载.",
  "message.inventory-full": "您的库存已满."
}

### Current Solution

I directly translated the English text of the mod into Chinese,hope you can use it

**Comment by Dunc4nNT** [comment]
Hey, thanks for sharing translations and making a github issue!
I'm currently working on a 1.1.0 release which will update some of the translation fields. However, I'll look at anything that's left unchanged and add the Chinese translations.

If you like, you could go to the "fishing" branch and check the file that's there as it'll be more up to date. Do note that I'm actively working on it, so it may be edited fairly often and may be better to wait for me to merge things into master.

**Comment by Dunc4nNT** [comment]
Hey, you can ignore all the pull request linking.

I've decided to **against** adding this as it would be adding outdated translations to the mod, which I cannot update myself.

I noticed a [Chinese mod translation](https://www.nexusmods.com/stardewvalley/mods/20688) already exists on Nexus, which will (likely) be more up do date as they can push out a new release whenever they want while I'd have to wait till it's reasonable to push a new release out. Though that page already exists, you're free to upload your own translations and publish them as well.

I hope you understand the reasoning, and feel free to ask if you need any help uploading translations on Nexus. And thanks for translating anyway!
