### ISSUE TITLE
Turkish Translate

### ISSUE THREAD

**Issue by Komaedaxs** [Dunc4nNT/StardewMods#14]
### Summary

Hello, I saw the mod [https://www.nexusmods.com/stardewvalley/mods/20985](url) and I want to translate it into Turkish, do I have permission?

### The Problem

.............

### Your Solution

..........

### Current Solution

............

### Extra Information

...........

**Comment by Dunc4nNT** [comment]
Hey, you're free to help translate the mod into languages it does not yet cover, or submit corrections for already existing ones.

**Comment by Komaedaxs** [comment]
{
  "message.config-reloaded": "Yapılandırma dosyası yeniden yüklendi.",

  "config.shops.shop-section": "Dükkanlar",
  "config.shops.pierres-general-shop.name": "Pierre'in Dükkanı",
  "config.shops.pierres-general-shop.tooltip": "Pierre'in dükkanı her zaman hizmete açıktır.",
  "config.shops.willys-fish-shop.name": "Willy'nin Balıkçı Dükkanı",
  "config.shops.willys-fish-shop.tooltip": "Willy'nin balıkçı dükkanı her zaman hizmete açıktır.",
  "config.shops.ice-cream-shop.name": "Dondurma Dükkanı",
  "config.shops.ice-cream-shop.tooltip": "Dondurma dükkanını her zaman hizmete açıktır",
  "config.shops.blacksmith-shop.name": "Demirci",
  "config.shops.blacksmith-shop.tooltip": "Clint'in demirci dükkanı her zaman hizmete açıktır.",
  "config.shops.carpenters-shop.name": "Marangoz",
  "config.shops.carpenters-shop.tooltip": "Robin'in marangoz dükkanı her zaman hizmete açıktır.",
  "config.shops.marnies-animal-shop.name": "Marnie'nin Hayvan Dükkanı",
  "config.shops.marnies-animal-shop.tooltip": "Marnie'nin hayvan dükkanı her zaman hizmete açıktır.",
  "config.shops.hospital-shop.name": "Hastane",
  "config.shops.hospital-shop.tooltip": "Hastanenin hizmeti her zaman herkese açıktır.",
  "config.shops.saloon-shop.name": "Yıldızkaydı Bar Salonu",
  "config.shops.saloon-shop.tooltip": "Yıldızkaydı bar salonu her zaman hizmete açıktır.",
  "config.shops.bookseller-shop.name": "Kitap Satıcısının Dükkanı",
  "config.shops.bookseller-shop.tooltip": "Kitap satıcısının dükkanı her zaman hizmete açıktır.",
  "config.shops.traveling-merchant-shop.name": "Seyyar Tüccar",
  "config.shops.traveling-merchant-shop.tooltip": "Seyyar tüccar her zaman hizmete açıktır (sadece yük arabası ormandayken).",
  "config.shops.resort-bar-shop.name": "Tatil Barı",
  "config.shops.resort-bar-shop.tooltip": "Tatil barı her zaman hizmete açıktır.",
  "config.shops.sandy-oasis-shop.name": "Vaha",
  "config.shops.sandy-oasis-shop.tooltip": "Sandy'nin Vahası her zaman hizmete açıktır"
}

here

**Comment by Dunc4nNT** [comment]
Thank you! I'll add it in for next release.

**Comment by Dunc4nNT** [comment]
Hey, I've added the translations you've sent in for the next release. Do note, I did add a few new config options which added some extra lines.

**Comment by Dunc4nNT** [comment]
Hi, extremely late update as I've been away from modding for a while. I believe you've already published the translations on your own nexusmods page, which I've decided is the preferred method from now on. Below you can find my reasoning for this decision, feel free to leave any questions or feedback.

> English is the only language fully supported by me, and guaranteed to be up to date.
> 
> There are various languages that have translations available to download and use on NexusMods. Do note that these may not always be up to date, as I can't guarantee support for those languages myself.
> 
> If the language you'd like to see has no translation, or it's outdated, feel free to create your own translations and publish them as a mod translation on NexusMods. **Please only upload the translation file and nothing else.** You can either upload it inside of a `SelfServe/i18n/` folder or as just the file. For extra information, take a look at the [translation wiki](https://stardewvalleywiki.com/Modding:Translations).
> 
> Due to me not being able to guarantee whether other languages are up to date, I prefer they be uploaded separately from this mod (so a mod translation on NexusMods). For players this means you'll have to look at the "Translations" tab on Nexus and check if the language you speak is on there. For translators this means you'll have to publish your translations on Nexus and publish updates after new releases yourself.
> 
> If you have a question regarding translations (whether it's about how to translate, how to upload them etc), feel free to contact me any way.
>
